### PR TITLE
Added nthnn/wtfC!?

### PR DESCRIPTION
**Pull request by nthnn**
Hello! First of all, great **awesome** list. Anyway, I've added [nthnn/wtfC!?](https://github.com/nthnn/wtfC) to Metaprogramming framework section.

Thank you!

### CODE REVIEW

**Comment by Hirrolot** [comment]
Hi! Looking at your repository, I don't believe it's a framework for metaprogramming, since metaprogramming means manipulating programs. The macros from the repository are simply shortcuts.

Also, I don't notice any conceptual difference with [Cello](https://github.com/orangeduck/Cello), which is also abundant with macro shortcuts for common patterns. It is generally a well-known practice (or rather a trick) to redefine common C patterns using macros; we can go with it as far as ["Let's Destroy C"](https://gist.github.com/shakna-israel/4fd31ee469274aa49f8f9793c3e71163#file-letsdestroyc-md), and probably even farther. So I don't see a compelling reason to add this repository to the list at the moment.

And I don't think that your `import` macro works. I've tried using it in godbolt and compilation failed.

**Comment by nthnn** [comment]
Hi! Thank you for your quick response. I won't be adding my repository on the list now.

**Comment by nthnn** [comment]
Also, `import` won't work in godbolt since it needs to be preprocessed first via `gcc -E ...`

**Comment by Hirrolot** [comment]
It doesn't work with `-E` either: https://godbolt.org/z/bfrP499zv.
The issue is that the C preprocessor doesn't allow `#` to be used other than to stringify macro arguments.

**Comment by nthnn** [comment]
Hi! Of course, it wouldn't really work on online compilers since it doesn't recursively preprocess source files. For starter, I am using clang 14.0.0. 

As you can see on the attached screenshot, I am using `-E` to output a preprocessed source file which would be expanding the line `import <stdio.h>` into `# include <stdio.h>`. Hence, the output of preprocessed file would need another round of preprocessing and exactly why I am doing in the second terminal command in the screenshot.

Screen Shot 2023-11-26 at 4 27 10 PM

**Comment by nthnn** [comment]
Here's a demo of preprocessing in godbolt: https://godbolt.org/z/qTsejcGd5

**Comment by Hirrolot** [comment]
Thanks, indeed -- for some reason, I received a godbolt error even after adding `-E`, but now I've just re-loaded the page and it worked.

It is interesting that, according to the C99 standard:

> Each `#` preprocessing token in the replacement list for a function-like macro shall be followed by a parameter as the next preprocessing token in the replacement list.

So this definition would not work:

```c
#define import() # include
```

Whereas the object-like version of `import` "works" perfectly (if we force macro preprocessing twice).

**Comment by nthnn** [comment]
Well, [nthnn/wtfC](https://github.com/nthnn/wtfC) actually have a compiling instruction for it... but yeah.

**Pull request closed without merging**
